---
language: python
services: docker

env:
  global:
    - ROLE_NAME: apache
  matrix:
    - MOLECULE_DISTRO: centos7
    - MOLECULE_DISTRO: centos6
    - MOLECULE_DISTRO: ubuntu1804
    - MOLECULE_DISTRO: ubuntu1604
    - MOLECULE_DISTRO: ubuntu1404
    - MOLECULE_DISTRO: debian9
    - MOLECULE_DISTRO: debian8

install:
  # Install test dependencies.
  - pip install molecule docker

before_script:


script:
  # Run tests.
  - molecule test
