# !/usr/bin/env ansible-playbook -i hosts --become -c paramiko
---

- name: Ansible Playbook for configuring Pi-Hole on Raspberry Pi
  hosts: webservers
  roles:
    - pi
  remote_user: pi
  become: true
