---
- name: Install packages
  package:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - dbus
      - git
  retries: 5
  delay: 2
  register: package_result
  until: package_result is succeeded

- name: "Setting hostname to 'pihole'"
  hostname:
    name: pihole
  register: reboot_device

- name: Ensures /etc/pihole dir exists
  become: true
  file:
    path: /etc/pihole
    state: directory

- name: Create pihole configuration
  become: true
  template:
    src: templates/setupVars.conf.j2
    dest: /etc/pihole/setupVars.conf
    owner: root
    group: root
    mode: 0644

- name: download pihole
  git:
    repo: 'https://github.com/pi-hole/pi-hole.git'
    dest: /home/Pi-hole
    depth: 1
    version: master
  retries: 5
  delay: 2
  register: git_result
  until: git_result is succeeded
  notify:
    - install pihole
    - set password

- name: download filterlists
  uri:
    url: https://v.firebog.net/hosts/lists.php?type=tick
    return_content: true
  retries: 5
  delay: 2
  register: filterlists
  until: filterlists is succeeded

- name: Ensures /etc/pihole/adlists.lists exists
  become: true
  copy:
    content: ""
    dest: /etc/pihole/adlists.list
    force: false
    group: root
    owner: root
    mode: 0644

- name: add default filterlists
  blockinfile:
    path: /etc/pihole/adlists.list
    block: |
      https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
      https://mirror1.malwaredomains.com/files/justdomains
      http://sysctl.org/cameleon/hosts
      https://zeustracker.abuse.ch/blocklist.php?download=domainblocklist
      https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt
      https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
      https://hosts-file.net/ad_servers.txt
    marker: "<!-- {mark} ANSIBLE MANAGED DEFAULT FILTERS -->"
    owner: root
    group: root
    mode: 0644
  notify: update filterlists

- name: add filterlists
  blockinfile:
    path: /etc/pihole/adlists.list
    block: "{{ filterlists.content }}"
    marker: "<!-- {mark} ANSIBLE MANAGED ADDITIONAL FILTERS -->"
    owner: root
    group: root
    mode: 0644
  notify: update filterlists
