---
- name: Install unbound
  package:
    name: unbound
    state: present

- name: Ensures /var/lib/unbound dir exists
  become: true
  file:
    path: /var/lib/unbound
    state: directory

- name: download root hints
  become: true
  get_url:
    url: https://www.internic.net/domain/named.cache
    dest: /etc/unbound/root.hints

- name: add cronjob to update root hints
  become: true
  copy:
    src: files/root_hints
    dest: "/etc/cron.weekly"
    owner: root
    group: root
    mode: 0755

- name: Create unbound config
  become: true
  template:
    src: templates/unbound_config.j2
    dest: /etc/unbound/unbound.conf
    owner: root
    group: root
    mode: 0644

- name: Start unbound service
  become: true
  service:
    name: unbound
    state: started
