---
- name: Converge
  hosts: all
  become: true

  vars:
    molecule_test: true
    ipv6_address: fe80::c9ac:6448:10e3:35f8

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=yes cache_valid_time=600
      when: ansible_os_family == 'Debian'
      changed_when: false

  roles:
    - role: pihole-ansible
